test: remove psx-mipsel from llvm_targets for now
    mq test-cases
        mq compile obj llvm_targets Debug mipsel-psx-eabi failure
    error: warning: MIPS-I support is experimental

This can be added back once this LLVM warning is removed.